### ISSUE TITLE
Problem with menu using high resolutions

### ISSUE THREAD

**Issue by Gu1Ka** [Eusth/HoneySelectVR#11]
When I use a higher resolution than 1600x900 (I tried 1980x1050 and 4K) the menu is only partially visible with the right and bottom side hidden. Also the pointer is locked within a smaller box, some button are then impossible to use (including H scene positions) so making the menu smaller don't fix the problem.

I configured the resolution with the english launcher available on anime sharing and not the native one, not sure if it changes anything.

Step to reproduce: 

-Change resolution to a high value (I used the english launcher mod)
-Try to click stuff on the right side of the menu, the pointer stop before the edge

**Comment by Eusth** [comment]
Are you using fullscreen or windowed mode? Does changing the mode in the launcher help?

Btw. I recommend using a low resolution anyway since it only affects the menu window.
