### ISSUE TITLE
Only for trial edition or for full version, too?

### ISSUE THREAD

**Issue by DasSmeagle** [Eusth/HoneySelectVR#12]
Hi,

The project descriptiona says: "This is an experimental mod for the trial edition of Honey Select..."

Is this true? Or does it work with the full version, too?

I tried with the full version and it is basically running, but after I (try to) start the game I am standing in a room, alone, and have no idea what to do ;) It is very possible this is because I just don't know how to use it, but if it works with full version, would be good to change that description, that's all ;)

Thanks,
- Oliver

**Comment by Eusth** [comment]
It's for the full version, yeah. Menu is attached to your Vive controllers or floating in front of you for other HMDs.
