### ISSUE TITLE
Vive H controller not working for some positions

### ISSUE THREAD

**Issue by Gu1Ka** [Eusth/HoneySelectVR#13]
For some positions scrolling on the trackpad doesn't do anything, the controller vibrate a little but the H doesn't proceed.

Position: BoobJob, Masturbation and most service in general. Insertions in the other hand seem to work well.

Step to reproduce:
1. Go in H mode
2. Select boobjob position
3. Try to play the position with the H controller

No exceptions in my vrlog.

**Comment by Eusth** [comment]
Try clicking into the transparent part of the menu with the laser pointer. Does that solve it?

**Comment by kideternal** [comment]
This seems like the same issue as #18 and has thus been fixed!

**Comment by Eusth** [comment]
Yup, thanks for the heads up.
