### ISSUE TITLE
Physics updates at a lower rate than normal fps?

### ISSUE THREAD

**Issue by thezig2** [Eusth/HoneySelectVR#15]
This may be beyond the scope of the mod, but it seems like breast physics aren't updating at every frame in an animation. It's not noticable when the model is a fair distance away, but at close range (i.e. when moving the camera to impersonate the male character during the "Lifting" animation) it's incredibly distracting to have the breasts moving at a different framerate than the rest of the body. 

After a little research, I found out that Unity updates physics at a fixed, arbitrary rate that's independent of normal fps. I'm not a programmer and can't say for sure, but I'd guess that the FixedUpdate for HS is running at 60fps, whereas my Rift forces everything else to 90.

Would it be possible to patch the game (using the same mechanism as the wide slider or ggmod) to change the fixed updates to 90 per second? Thanks!

**Comment by Eusth** [comment]
Yup, it's possible to change the fixed update time, and in fact I've been changing it to 1/90 since day one.

It's possible that HS overwrites my value, though -- I'll have to check.

**Comment by thezig2** [comment]
Thanks for looking into it.

**Comment by chickenchaser9** [comment]
I too have experienced this, at first I thought it was my graphics card, but I'm running a 980TI. with an i7. 
With more reports of this, I'm guessing it may be a bug.

**Comment by Eusth** [comment]
Can you check if the latest update fixes this issue`?

**Comment by nitrixs** [comment]
It does for me.
