### ISSUE TITLE
Oculus Touch Controllers Touchpad issue

### ISSUE THREAD

**Issue by Buckweed1** [Eusth/HoneySelectVR#22]
Everything thing works great with the touch controllers apart from the touchpad as the oculus had joysticks. Any chance you could add a work around?

**Comment by Eusth** [comment]
I just largely rewrote the warp tool to work better with Touch controllers (but this change hasn't made it to Honey Select VR yet).

It shouldn't be hard to also optimize the play tool to control animations with the Touch controllers, but I don't know when I'll be able to get to it. I'm currently not very interested in Honey Select.

**Comment by Buckweed1** [comment]
When you get to it it'll be very much appreciated!

**Comment by dondi99** [comment]
I really hope you can find the time and interest for one more update for the touch controllers. They work so close to perfect already and just need some way to simulate the mouse scroll wheel to control animations.
