### ISSUE TITLE
Studio

### ISSUE THREAD

**Issue by Jmi95110** [Eusth/HoneySelectVR#23]
Hi,
You did a great mod for HS, is it possible to use it with the studio?

**Comment by chickenchaser9** [comment]
Try it out. I've heard of people taking the vr mod, changing the name of the .exe to honeystudioVR.exe and. Then copying the info in the honey select 64 bit folder into the honey studio 64 bit folder. Haven't gotten a chance to try yet as I'm traveling on vacation.

Let me know! ^-^

**Comment by chickenchaser9** [comment]
Just confirmed this works.
