### ISSUE TITLE
Game crashes randomly with new update

### ISSUE THREAD

**Issue by Sergster1** [Eusth/HoneySelectVR#24]
[Logs from modded game](https://github.com/Eusth/HoneySelectVR/files/676530/2016-12-28_220046.zip) 
[Logs from fresh install](https://github.com/Eusth/HoneySelectVR/files/676531/2016-12-28_220314.zip)

**Comment by Trichinosis** [comment]
I see this as well.  I cannot get shaders to work with `<ApplyShaders>true</ApplyShaders>` (revert to 0.3 and they do work), and the game crashes either at the start button or shortly into the game.

[2016-12-28_215406.zip](https://github.com/Eusth/HoneySelectVR/files/676663/2016-12-28_215406.zip)
[vr.log.zip](https://github.com/Eusth/HoneySelectVR/files/676664/vr.log.zip)

Not sure if the shaders issue is connected or another issue.

**Comment by Eusth** [comment]
Can you check if 0.4.1 fixes this issue and close the issue if it does?

**Comment by Trichinosis** [comment]
0.4.1 is solid for me.  Shaders work, and crashes appear to be resolved.  Thanks!

I believe Sergster1 needs to close, if it works for him as well.

**Comment by Sergster1** [comment]
It's solid for me as well! Thanks for the great work!
