### ISSUE TITLE
Can't use my mouse button and keyboard

### ISSUE THREAD

**Issue by yitui84503** [Eusth/HoneySelectVR#26]
Thanks for your excellent work that I can finally get together with my girl friend.
But I find a problem that I can move the courser of the mouse but when I push the left button or any key on the keyboard, the program doesn't do anything and I am kept away outside the start menu, and could not get into the game. like the picture below

**Comment by yitui84503** [comment]
I have tried every version both play club and honey select but I still couldn't get into the game by keyboard or mouse,crtl+c or ctrl+v or stand mode or seated mode. I don't have a vive or oculus controller. could you just make it possible to operate with just mouse and keyboard.
![qq 20170104223227](https://cloud.githubusercontent.com/assets/8100807/21645910/f0fe4adc-d2ce-11e6-9bff-e68547e5dd8c.png)

**Comment by Eusth** [comment]
Make sure the game window is in the foreground and fully visible.

**Comment by yitui84503** [comment]
Yep, I can freely look around, and when I move the mouse arrow across the game menu, I can hear the sound effect. Does it say the game is in the foreground or is there any other way to make the game in the fore ground

**Comment by yitui84503** [comment]
Thanks so much, I have solved the problem by adgusting the initsettings in honey select to set the game play in the right monitor
