### ISSUE TITLE
Scaling by pressing touchpad not working in latest release

### ISSUE THREAD

**Issue by deinlandel** [Eusth/HoneySelectVR#28]
In latest VR mod release, scaling by pressing touchpad and moving controller isn't working anymore. Is this intended?

**Comment by Eusth** [comment]
Yup. Scaling is now possible as described in the release notes.

**Comment by deinlandel** [comment]
I see... But the problem is, new scaling is unusable with one controller. Up until now, the game was fully playable with only one controller.

**Comment by Eusth** [comment]
Yeah, but it also made the controls a lot more erratic, i.e. many people who hadn't read the manual were confused by the sudden change of scale.

Scale doesn't need to be adjusted as often as other things, so I went for the more intuitive albeit two-handed method.
