### ISSUE TITLE
Unable to start in vr

### ISSUE THREAD

**Issue by phnordmann** [Eusth/HoneySelectVR#36]
When I trie to start HS in vr I get a error "could not find honeyselect.exe. Dont know of i have installed the files right. I copied the files into the main folder where the honeyselect_64 is. 
Can anyone help me?

**Comment by Eusth** [comment]
Sounds like you extracted your files into the wrong folder. Next to "HoneyStudio_64VR.exe" there should be a file "HoneyStudio_64.exe".

Make sure that the file mentioned in the error message really does exist.

**Comment by phnordmann** [comment]
I have the full game, is that a problem. Is this only for the full game. In wich folder do I find HoneySelect.exe. 

Thank you for answering
