### ISSUE TITLE
no control box in vr (oculus rift)

### ISSUE THREAD

**Issue by Yatslol** [Eusth/HoneySelectVR#38]
hi, my game worked great until recently but now i have no control box or IK target, i also can't move using the "grab-moving" button and i get this http://imgur.com/P2Y3dRx on my monitor.
i tried to reinstall the game but it doesn't work
maybe it's because of the latest rift update ?

**Comment by Yatslol** [comment]
so ... i tried to reinstall the game several times, on a clean install of windows and i still can't move the character/animation and grab-move the camera
i have no idea what i am missing

**Comment by Eusth** [comment]
- Do you have any other plugins installed? Try without them.
- What does your `vr.log` and your `HoneyStudio_64_Data/output_log.txt` say?

**Comment by Yatslol** [comment]
i removed two folders (Ggmod_cfg and SkinTexMod) and GgmodForHS.dll, GgmodForHS_Studio.dll and SkinTexMod.dll (leaving only honeyselectVR files). Nothing has changed.

[vr & output files.zip](https://github.com/Eusth/HoneySelectVR/files/785924/vr.output.files.zip)

**Comment by ghost** [comment]
work again with the EMF patch 0.4. thank you for your help and your awesome mod !
