### ISSUE TITLE
What's the motion controller button to replace the Wheel? (Oculus Rift)

### ISSUE THREAD

**Issue by Jogger45** [Eusth/HoneySelectVR#39]
I seem to find it, whichever controller has the Build wheel on it, I can lock status and seem to find the trigger to start it. But I can't seem to make it increase or decrease, please reply soon!

**Comment by Eusth** [comment]
> In the play tool, move the stick right to increase speed, move it left to decrease speed

Make sure that the cursor is *not* on any GUI element or it will not work. I've fixed this in a local build but have been too lazy to update.

**Comment by Jogger45** [comment]
Yup, thanks so much
