### ISSUE TITLE
Installation tutorial

### ISSUE THREAD

**Issue by phnordmann** [Eusth/HoneySelectVR#42]
Hi 

Sorry for asking. Is there any one here who can explain 
how to install this. And is it only for the trial verdion or does it also work in the full game. 
I have copy pasted the files into the main Illusion folder where the honeyselect32 and 64 files are. 
When I start the Honeyselectvr file I get an error saying it can find the exe file. 

Please help

**Comment by Eusth** [comment]
Can you make a screenshot of the folder + error message?

**Comment by phnordmann** [comment]
Here is the folder I put the files and the error message

![bilde](https://cloud.githubusercontent.com/assets/25436788/23016427/caf7d3f6-f436-11e6-8a0c-6d20fac63f4b.png)

**Comment by Eusth** [comment]
OK, thanks! Your program file is not named correctly -- it should be "HoneySelect_64VR" *not* "honeyselect_64vr". Did you rename the files...?

Also, I recommend using the latest version.

**Comment by phnordmann** [comment]
That did it.
Thank you so much,
