### ISSUE TITLE
Render chaperone behind character models.

### ISSUE THREAD

**Issue by ACIIL** [Eusth/HoneySelectVR#58]
Running from the small room size, the chaperone is always overly sensitive, as you may guess we tend to spend most of the time on the floor, where the controllers or headset will trigger the grid; or by the computer keyboard, which tends to be on a corner of the chaperone. A grid covering the waifu creates a confusing depth problem with the closer models rendering behind the far grid.

Can you please make the chaperone render behind player models? If possible i can help debug as i been studying Unity, and just a little bit in Unity VR mythology.

**Comment by deinlandel** [comment]
AFAIK chaperone is overlayed on top of rendered image by SteamVR compositor, so mixing it with scene geometry may be complicated or even impossible.

You can turn chaperone off using openvr advanced settings. Or set chaperone trigger distance to minimum.

**Comment by ACIIL** [comment]
I guess we must work within our means. That openvr advanced settings program works ok for the situation, i am surprised it never turn up when searching results about chaperone visibility control. Thank you.

Still, controlling rendering order for this Unity hack should be considered. I'm going to close my issue as i can work with the new settings.
