### ISSUE TITLE
Can't use the menu with oculus rift

### ISSUE THREAD

**Issue by AdamAkkari** [Eusth/HoneySelectVR#75]
Hi,

I followed [this tutorial](https://www.reddit.com/over18?dest=https%3A%2F%2Fwww.reddit.com%2Fr%2Fadultvrgames%2Fcomments%2F6cio5b%2Fhoneyselect_englishvr_guide_for_fully_updated%2F) to install Honey Select VR. The game launch perfectly, I'm able to move around, everything works fine except the menu. I can see it, when I approach one of the oculus touch near the menu I can see the laser thingy, but no matter what button I press, nothing happen :/

**Comment by crusnik** [comment]
Make sure the Honey Select Window has focus in Windows.

**Comment by AdamAkkari** [comment]
It works now, thank you for the quick answer !
