### ISSUE TITLE
Gamepad control

### ISSUE THREAD

**Issue by kupo666** [Eusth/HoneySelectVR#8]
Hi, the readme says you can use the gamepad in sitting mode. Is that implemented yet? Because my xbox gamepad doesnt work in the game. It works with Playclub VR.

**Comment by Eusth** [comment]
Nope, not implemented. Readme was copy & pasted from Play Club and seems like I forgot to remove that part.

**Comment by kupo666** [comment]
Right, good to know. Are you planning to implement it? Not a huge deal since Touch is out soon, just wondering.

**Comment by Eusth** [comment]
Hm... depends on the general demand, but for the time being there are other things that have to be done first. It wouldn't be *that* hard to port the code over, though.

For the time being, there's still the official VR patch for controller support.
